### ISSUE TITLE
Search Mode All

### ISSUE THREAD

**Issue by pareshmithra** [katzwebservices/gv-snippets#2]
I have issues with search bar. I have clicked on match all fields. But it is not working. Even if I search with one field it is showing results. I installed your GravityView Mod: Search Mode "All" snippet also. But no use. Please help me.

**Comment by pareshmithra** [comment]
Why this issue is closed without any comment?

**Comment by rafaehlers** [comment]
@pareshmithra This is not a place to ask for support related questions. Use this form instead: https://gravityview.co/support/
